package vn.hoangminh.erp.Ht4NhanSu.service;
import jakarta.validation.Validator; import java.time.LocalDateTime; import java.util.*; import java.util.stream.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import vn.hoangminh.erp.Ht4NhanSu.domain.*; import vn.hoangminh.erp.Ht4NhanSu.dto.Ht4Dto.*; import vn.hoangminh.erp.Ht4NhanSu.repository.*; import vn.hoangminh.erp.common.exception.LoiNghiepVuException; import vn.hoangminh.erp.common.permission.*; import vn.hoangminh.erp.common.security.NguoiDungHienTai; import vn.hoangminh.erp.common.sequence.*;
@Service @RequiredArgsConstructor public class Ht4Service {
 private final NhanVienRepository nv; private final PhongBanRepository pb; private final ChucVuRepository cv; private final TrangThaiNhanVienRepository tt; private final YeuCauCapNhatHoSoRepository yeuCau; private final MaChungTuService ma; private final QuyenService quyen; private final Validator validator;
 private NguoiDungHienTai nd(ChucNang c){var n=NguoiDungHienTai.hienTai();quyen.yeuCauChucNang(n.vaiTro(),c);return n;} private NhanVien get(String id){return nv.findById(id).orElseThrow(()->LoiNghiepVuException.khongTimThay("ht4.khontimthay"));} private void valid(Object x){if(!validator.validate(x).isEmpty())throw LoiNghiepVuException.duLieu("loi.dulieu.khonghople");}
 private HoSoView view(NhanVien n){return new HoSoView(n.getMaNV(),n.getHoTen(),n.getNgaySinh(),n.getGioiTinh(),n.getSoDienThoai(),n.getDiaChi(),n.getEmail(),n.getPhongBan()==null?null:n.getPhongBan().getMaPhongBan(),n.getPhongBan()==null?null:n.getPhongBan().getTenPhongBan(),n.getChucVu()==null?null:n.getChucVu().getMaChucVu(),n.getChucVu()==null?null:n.getChucVu().getTenChucVu(),n.getTrangThai()==null?null:n.getTrangThai().getMaTrangThai(),n.getTrangThai()==null?null:n.getTrangThai().getTenTrangThai(),n.getNgayVaoLam());}
 @Transactional(readOnly=true) public List<HoSoView> timKiem(String q,String phong,String chuc,String trang){nd(ChucNang.HT4_TIM_KIEM_HO_SO); return nv.findAll().stream().filter(n->q==null||q.isBlank()||n.getMaNV().contains(q)||n.getHoTen().toLowerCase().contains(q.toLowerCase())).filter(n->phong==null||phong.equals(n.getPhongBan()==null?null:n.getPhongBan().getMaPhongBan())).filter(n->chuc==null||chuc.equals(n.getChucVu()==null?null:n.getChucVu().getMaChucVu())).filter(n->trang==null||trang.equals(n.getTrangThai()==null?null:n.getTrangThai().getMaTrangThai())).map(this::view).toList();}
 @Transactional public HoSoView them(HoSoInput i){nd(ChucNang.HT4_THEM_HO_SO);valid(i); NhanVien n=new NhanVien();n.setMaNV(ma.capMa(LoaiChungTu.NHAN_VIEN)); map(n,i);return view(nv.save(n));}
 @Transactional public HoSoView sua(String id,HoSoInput i){nd(ChucNang.HT4_SUA_HO_SO);valid(i);NhanVien n=get(id);map(n,i);return view(nv.save(n));}
 private void map(NhanVien n,HoSoInput i){n.setHoTen(i.hoTen());n.setNgaySinh(i.ngaySinh());n.setGioiTinh(i.gioiTinh());n.setSoDienThoai(i.soDienThoai());n.setDiaChi(i.diaChi());n.setEmail(i.email());n.setNgayVaoLam(i.ngayVaoLam());n.setPhongBan(i.maPhongBan()==null?null:pb.findById(i.maPhongBan()).orElseThrow(()->LoiNghiepVuException.khongTimThay("ht4.khontimthay")));n.setChucVu(i.maChucVu()==null?null:cv.findById(i.maChucVu()).orElseThrow(()->LoiNghiepVuException.khongTimThay("ht4.khontimthay")));n.setTrangThai(i.maTrangThai()==null?null:tt.findById(i.maTrangThai()).orElseThrow(()->LoiNghiepVuException.khongTimThay("ht4.khontimthay")));}
 @Transactional public HoSoView trangThai(String id,TrangThaiInput i){nd(ChucNang.HT4_QUAN_LY_TRANG_THAI);NhanVien n=get(id);n.setTrangThai(tt.findById(i.maTrangThai()).orElseThrow(()->LoiNghiepVuException.khongTimThay("ht4.khontimthay")));return view(nv.save(n));}
 @Transactional(readOnly=true) public HoSoView cuaToi(){var n=NguoiDungHienTai.hienTai();nd(ChucNang.HT4_XEM_HO_SO_CA_NHAN);return view(get(n.maNV()));}
 @Transactional(readOnly=true) public HoSoView chiTiet(String id){nd(ChucNang.HT4_XEM_HO_SO);return view(get(id));}
 private YeuCauView yc(YeuCauCapNhatHoSo y){return new YeuCauView(y.getMaYeuCau(),y.getMaNV(),nv.findById(y.getMaNV()).map(NhanVien::getHoTen).orElse(null),y.getNoiDung(),y.getTrangThai(),y.getThoiGianGui(),y.getNguoiXuLy(),y.getThoiGianXuLy(),y.getPhanHoi());}
 /** [G21] Yêu cầu được lưu vào CSDL để nhân sự xử lý, thay cho hàng đợi trong bộ nhớ trước đây. */
 @Transactional public YeuCauView yeuCau(YeuCauInput i){var n=nd(ChucNang.HT4_GUI_YEU_CAU_CAP_NHAT);valid(i);var y=new YeuCauCapNhatHoSo();y.setMaNV(n.maNV());y.setNoiDung(i.noiDung());y.setTrangThai("Chờ xử lý");y.setThoiGianGui(LocalDateTime.now());return yc(yeuCau.save(y));}
 /** Nhân sự xem toàn bộ yêu cầu; nhân viên thường chỉ xem yêu cầu của chính mình. */
 @Transactional(readOnly=true) public List<YeuCauView> danhSachYeuCau(){var n=NguoiDungHienTai.hienTai();boolean nhanSu=quyen.coChucNang(n.vaiTro(),ChucNang.HT4_QUAN_LY_TRANG_THAI);if(!nhanSu)nd(ChucNang.HT4_GUI_YEU_CAU_CAP_NHAT);return (nhanSu?yeuCau.findByOrderByThoiGianGuiDesc():yeuCau.findByMaNVOrderByThoiGianGuiDesc(n.maNV())).stream().map(this::yc).toList();}
 @Transactional public YeuCauView xuLyYeuCau(Integer id,XuLyYeuCauInput i){var n=nd(ChucNang.HT4_QUAN_LY_TRANG_THAI);valid(i);if(!"Đã xử lý".equals(i.trangThai())&&!"Từ chối".equals(i.trangThai()))throw LoiNghiepVuException.duLieu("ht4.trangthaiyeucau");var y=yeuCau.findById(id).orElseThrow(()->LoiNghiepVuException.khongTimThay("ht4.khontimthay"));if(!"Chờ xử lý".equals(y.getTrangThai()))throw LoiNghiepVuException.xungDot("ht4.yeucaudaxuly");y.setTrangThai(i.trangThai());y.setPhanHoi(i.phanHoi());y.setNguoiXuLy(n.maNV());y.setThoiGianXuLy(LocalDateTime.now());return yc(y);}
}
