package vn.hoangminh.erp.Ht3DieuPhoi.controller;
import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.web.bind.annotation.*; import java.util.*; import vn.hoangminh.erp.Ht3DieuPhoi.dto.Ht3Dto.*; import vn.hoangminh.erp.Ht3DieuPhoi.service.Ht3Service;
@RestController @RequestMapping("/api/ht3") @RequiredArgsConstructor public class Ht3Controller { private final Ht3Service s;
 @GetMapping("/tai-xe") public List<TaiXeView> tx(){return s.taiXe();} @GetMapping("/phuong-tien") public List<PhuongTienView> pt(){return s.phuongTien();} @GetMapping("/don-san-sang") public List<vn.hoangminh.erp.Ht1DonHang.domain.DonHang> donSanSang(){return s.donSanSang();} @GetMapping("/chuyen") public List<ChuyenView> ds(){return s.danhSach();}
 @GetMapping("/don-chon-duoc") public List<vn.hoangminh.erp.Ht1DonHang.domain.DonHang> donChonDuoc(@RequestParam(required=false)Integer maChuyen){return s.donChonDuoc(maChuyen);}
 @PostMapping("/chuyen") public ChuyenView chuyen(@Valid @RequestBody ChuyenInput i){return s.lapKeHoach(i);}
 @PutMapping("/chuyen/{ma}") public ChuyenView suaChuyen(@PathVariable Integer ma,@Valid @RequestBody ChuyenInput i){return s.capNhatKeHoach(ma,i);}
 @DeleteMapping("/chuyen/{ma}") public void xoaChuyen(@PathVariable Integer ma){s.xoaChuyen(ma);} @PostMapping("/phan-cong/{ma}") public ChuyenView phanCong(@PathVariable Integer ma,@Valid @RequestBody PhanCongInput i){return s.phanCong(ma,i);}
 @PostMapping("/chuyen/{ma}/phe-duyet") public ChuyenView duyet(@PathVariable Integer ma){return s.pheDuyet(ma);} @PostMapping("/chuyen/{ma}/yeu-cau-dieu-chinh") public ChuyenView sua(@PathVariable Integer ma,@RequestBody Map<String,String> i){return s.yeuCauDieuChinh(ma,i.get("lyDo"));}
 @GetMapping("/nhiem-vu-cua-toi") public List<NhiemVuView> nhiemVu(){return s.nhiemVuCuaToi();} @GetMapping("/lich-su-ca-nhan") public List<LichSuGiaoView> lichSuCaNhan(){return s.lichSuCaNhan();}
 @GetMapping("/tra-cuu") public List<TraCuuView> traCuu(@RequestParam(required=false)String maDonHang,@RequestParam(required=false)String bienSo,@RequestParam(required=false)java.time.LocalDate tuNgay,@RequestParam(required=false)java.time.LocalDate denNgay,@RequestParam(required=false)String tuKhoa){return s.traCuu(maDonHang,bienSo,tuNgay,denNgay,tuKhoa);} @PostMapping("/chuyen/{ma}/nhan") public ChuyenView nhan(@PathVariable String ma){return s.nhanDon(ma);} @PostMapping("/don-hang/{ma}/nhan") public ChuyenView nhanDon(@PathVariable String ma){return s.nhanDonHang(ma);}
 @PostMapping("/su-co") public SuCoView suCo(@Valid @RequestBody SuCoInput i){return s.baoCaoSuCo(i);} @GetMapping("/su-co") public List<SuCoView> dsSuCo(){return s.danhSachSuCo();}
 @PutMapping("/su-co/{ma}") public SuCoView xuLySuCo(@PathVariable Integer ma,@Valid @RequestBody XuLySuCoInput i){return s.xuLySuCo(ma,i);}
 @DeleteMapping("/su-co/{ma}") public void thuHoiSuCo(@PathVariable Integer ma){s.thuHoiSuCo(ma);} @PostMapping("/chuyen/{ma}/moc-hanh-trinh") public MocView moc(@PathVariable Integer ma,@Valid @RequestBody MocInput i){return s.moc(ma,i);} @GetMapping("/chuyen/{ma}/moc-hanh-trinh") public List<MocView> dsMoc(@PathVariable Integer ma){return s.mocHanhTrinh(ma);}
 @PostMapping("/don-hang/{ma}/hoan-tat") public ChuyenView hoanTat(@PathVariable String ma,@Valid @RequestBody MinhChungInput i){return s.hoanTat(ma,i);} @GetMapping("/chuyen/{ma}/su-co") public List<SuCoView> suCo(@PathVariable Integer ma){return s.suCo(ma);}
}
